services:
  #nginx_default:
  #  build: ./docker_folder/nginx_default
  #  ports:
  #  - '80:80'
  nginx:
    build: ./docker_folder/nginx
    ports:
    - '80:80'
    volumes:
      - type: bind
        source: ./src
        target: /usr/share/nginx/html/www
#volumes:
#  myapp:
  ##php_fpm:
  ##  build: ./docker_folder/php8.4_fpm
  ##  ports:
  ##    - "9000:9000"
    #depends_on:
    #- web1
    #- web2

  #redis:
  #  image: redis
  #  ports:
  #    - '6379:6379'
  #web1:
  #  restart: on-failure
  #  build: ./web
  #  hostname: web1
  #  ports:
  #    - '81:5000'
  #web2:
  #  restart: on-failure
  # build: ./web
  #  hostname: web2
  #  ports:
  #    - '82:5000'
  
