###version: '3' ?
##service:
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./src
        target: /app/static
volumes:
  myapp:
    #./public:/app/public:ro:
    #./src/nginx/conf.d:/etc/nginx/conf.d:ro:
    #./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro:
    #./src/nginx/ssl:/etc/nginx/ssl:ro:
  #php_fpm:
  #  build: ./php8.4_fpm
  #  ports:
  #    - "9000:9000"
  #php_my_admin:
  #  build: ./php_my_admin
  #db_mysql:
    ##image: postgres:13
  #  build: ./db_mysql
    #environment:
    #  POSTGRES_USER: example
    #  POSTGRES_DB: exampledb
    #docker compose -f 'docker_folder/docker-compose.yaml' up -d --build